### ISSUE TITLE
VariableManager Design Question (and misc recommendations)

### ISSUE THREAD

**Issue by TheCreatorJames** [ellenhebert/NewLang#1]
In a few other class files, I see that you implemented maps, so it is clear that you know how to use them. 

Just a small quesiton, why are you using two separate lists in the Variable Manager class instead of just using a Map? 

Also, just a recommendation, you might want to consider making your code a bit more modular, so that you can add in new commands and variable types without modifying the main parser code.

You could give each variable type a separate class containing a method that allows the various operators to be passed in and be executed. This will break your code apart and make it easier to add new data types later on (you could even extend your language to allow object-oriented programming). 

Also, you might want to add an "Extension" class that allows you to add new commands to the parser without modifying the parser code. Commands like "read" and "write" could be put into a "ConsoleExtension".  This will allow people to use this language inside of video games easily, as they'd be able to add support for their own "read" commands (which might open a dialog box in their game).

**Comment by ellenhebert** [comment]
Before I implemented VariableManager, variables were stored in a map.

With the new system, after the code is parsed, all variables are swapped with id numbers. For example, if a program had two variables 'tree' and 'bush', tree would become 0 and bush would become 1. The idea is to allow faster lookup of the variable values: to get the value of 'tree', it would just have to get the first value in the ArrayList, rather than looking up 'tree' in a HashMap. That would end up being a substantial speed boost in loops that execute thousands of times.

However, I think there's only a negligible benefit to it at the moment since all code is stored as strings, which have to be ran through Integer.parseInt() before being looked up in the ArrayList. In the future when numbers are stored as literal numbers rather than strings, there should be a large improvement. I also want to replace the ArrayList with an array for further speedup (since the parser can determine how many variables exist ahead of time).

The second ArrayList in VariableManager links the name of the variable for that id. For example, position 0 would say 'tree'.

I definitely do need to make the code more modular. Part of why I stopped working on this interpreter was frustration with the direction that it was moving in. Most of the code is all clustered in TreeElement and it's proving to be a pain to separate. I will resume working on it soon, hopefully.

I will be adding separate classes for the various data types. Although I doubt objects will ever happen.

Adding a Function class has also been on my mind. The way all the commands are hardcoded in TreeElement was for two reasons. First, it was simpler to write and more compact (although clunkier to deal with later). Second, it's faster. I wrote an interpreter similar to this one in January/February, where every command was stored in a separate class and implemented an interface called 'Command'. The number of classes in the project became unwieldy, and every time a function was called (even a simple operator like +, -, or =) it required a HashMap lookup. I will add a similar interface to this project, while keeping a lot of the functions that are currently in TreeElement in there.

I think there already is a sort of read command. I'm going to add a full REPL eventually.
